name: Hello World Workflow

on:
  push:
    branches:
      - main # Triggers on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout the repository code

      - name: Print Hello World
        run: echo "Hello, GitHub Actions World!" # Executes a shell command
